### ISSUE TITLE
Strange behaviour with dockerImage and npm namepace.

### ISSUE THREAD

**Issue by MrBlenny** [esatterwhite/semantic-release-docker#25] opened 2022-07-04 06:54 UTC
If for example I configure a `release.config.js` using:

```js
        [
            "@codedependant/semantic-release-docker",
            {
                "dockerImage": "ghcr.io/some-org/some-package-name",
                "dockerLogin": false,
            }
        ],
```

But in my `package.json` I have:

```js
{
  "name": "@some_npm_namespace/some-package-name-that-might-be-different",
  ....
 ```
 
 It will build with `docker build --quiet --tag some-npm-namespace/ghcr.io/some-org/some-package-name`, [prefixing the `dockerImage` with the npm namespace. A workaround for now is to remove the npm namespace.

**Comment by esatterwhite** [comment] 2022-07-15 19:16
@MrBlenny Thanks for the report.
This is intended behavior currently. I think this may just be a mis configuration

there is are a few options that are used to construct the full docker image ID

* dockerProject - The project or repository name to publish the image to. If not specified, the package scope is used, other wise, defaults to null.
* dockerRegistry - the host name of the registry where images should be pushed
* DockerImage - Just the name of the image.

So you should break up the values for dockerImage up, and I think it should be enough to specify project as null.

```json
{
  "dockerRegistry": "ghcr.io",
  "dockerProject": null,
  "dockerImage": "some-package-name"
}
```
Let me know if this resolves the issue

**Comment by esatterwhite** [comment] 2023-07-08 04:26
Closing as I believe this is resolved. If you're still having trouble, please do let me know, or re-open the issue

**Closed as completed by esatterwhite** 2023-07-08 04:26 UTC
Labels: question
